### ISSUE TITLE
[问题]请问PC端可以全屏吗,好像没找到全屏按钮

### ISSUE THREAD

**Issue by ameaninglessname** [iiijam/ice_live_viewer#11]
**你的功能请求是否与一个问题有关？请描述。**
没找到全屏按钮

_另外请问有计划支持多窗口吗?
比如打开多个直播间/ 看直播的同时可以继续添加直播间 / 按直播间状态排序,分类等_

**描述你想要的解决方案**
可以支持全屏播放,窗口全屏等

**补充**
![image](https://user-images.githubusercontent.com/20263103/193410976-dfe50610-cfc5-4510-8cd5-a62b8a0638c1.png)

- [x] 我已经阅读了相关内容并且描述准确

**Comment by iiijam** [comment]
1.没找到全屏按钮 上游插件似乎有问题 全屏后无法退出
2.多窗口 直接另行启动就行 不会影响之前的
