### ISSUE TITLE
[bug]该斗鱼房间无法解析

### ISSUE THREAD

**Issue by xiaoze183** [iiijam/ice_live_viewer#12]
https://www.douyu.com/topic/RMR10_4?rid=209783

Exception: {error: 742017, msg: 后端服务异常, data: }
#0      Douyu._getRoomStreamInfo (package:ice_live_viewer/utils/http/douyuparser.dart:37)
<asynchronous suspension>
#1      Douyu._getRoomUrl (package:ice_live_viewer/utils/http/douyuparser.dart:80)
<asynchronous suspension>
#2      Douyu.getRoomFullInfo (package:ice_live_viewer/utils/http/douyuparser.dart:124)
<asynchronous suspension>
#3      _FutureBuilderState._subscribe.<anonymous closure> (package:flutter/src/widgets/async.dart:628)
<asynchronous suspension>

**Comment by iiijam** [comment]
只要是正常直播的都可以看，但是遇到`后端服务异常`一般是切换直播状态或者在回放
