### ISSUE TITLE
[bug]B站直播无法正常播放

### ISSUE THREAD

**Issue by dabao0101** [iiijam/ice_live_viewer#14]
**在提出问题时，请确保您已经阅读了以下内容**
 - [README](README.md)

 - [ISSUE](https://github.com/iiijam/ice_live_viewer/issues?q=)

 - [如何有效地报告 Bug](https://www.chiark.greenend.org.uk/~sgtatham/bugs-cn.html)

 - [提问的智慧](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md)

在阅读完以上内容后，如果您仍然有问题，请删除自第一行加粗内容起至下一行加粗内容的所有文字，在最后一行的[]中填写x，然后描述问题。

**请勿删除自此行之后加粗的模板！**

**描述错误**
测试斗鱼TV平台正常播放，但是哔哩哔哩网站直播流时无法正常播放，显示黑屏，FLV切换到m3u8格式依旧无法正常播放，具体表现为黑屏，并且过一段时间自动结束进程。

**重现**
重现该行为的步骤。
1. 转到 '哔哩哔哩直播间'
2. 点击 '播放'
4. 看到黑屏画面

**预期的行为**
简明扼要地描述你期望发生的情况。

**屏幕截图**
如果适用，添加屏幕截图以帮助解释你的问题。
![图片](https://user-images.githubusercontent.com/56470191/201592630-a06c3481-6c45-4a78-8758-21f4a02d096c.png)
![图片](https://user-images.githubusercontent.com/56470191/201592734-36c2ba0e-bdeb-4f0c-8596-651c975b1729.png)

**设备信息（请填写以下信息）：**
- 操作系统： ：Windows
- 版本： Windows 11 21H2

**额外的背景**
在这里添加关于问题的任何其他背景。

[] 我已经阅读了相关内容并且描述准确

**Comment by iiijam** [comment]
已经在 4bd15a005e38bc7d82b3f5455f61550eb556d8d2 修复，版本号更新至[0.3.6](https://github.com/iiijam/ice_live_viewer/releases/tag/v0.3.6) 看看是否能正常观看

**Comment by dabao0101** [comment]
感谢开发者大大，可能因为国内地理位置原因，目前0.3.6版本基本三平台都可以正常播放了，太牛啦❤️❤️❤️
________________________________
发件人: Angelo Hamlet ***@***.***>
发送时间: 2022年11月20日 22:54
收件人: iiijam/ice_live_viewer ***@***.***>
抄送: dabao0101 ***@***.***>; Author ***@***.***>
主题: Re: [iiijam/ice_live_viewer] [bug]B站直播无法正常播放 (Issue #14)


已经在 4bd15a0<https://github.com/iiijam/ice_live_viewer/commit/4bd15a005e38bc7d82b3f5455f61550eb556d8d2> 修复，版本号更新至0.3.6<https://github.com/iiijam/ice_live_viewer/releases/tag/v0.3.6> 看看是否能正常观看
