### ISSUE TITLE
斗鱼部分链接导入报错

### ISSUE THREAD

**Issue by PieJEed** [iiijam/ice_live_viewer#17]
**描述错误**
斗鱼部分链接导入报错

**重现**
重现该行为的步骤。
1. 使用CTRL+C快捷键复制斗鱼直播间链接
2. 点击IceLiveViewer的加号
3. 使用CTRL+V快捷键粘贴链接后添加直播间
4. 看到错误

**预期的行为**
添加斗鱼直播间  例如https://www.douyu.com/5743523

**屏幕截图**
https://pic.imgdb.cn/item/63a180f0b1fccdcd36991515.png

**设备信息（请填写以下信息）：**
- 操作系统： Windows
- 版本： Windows 10 21H2

**额外的背景**
Exception: {error: 742017, msg: 后端服务异常, data: }
#0      Douyu._getRoomStreamInfo (package:ice_live_viewer/utils/http/douyuparser.dart:37)
<asynchronous suspension>
#1      Douyu._getRoomUrl (package:ice_live_viewer/utils/http/douyuparser.dart:80)
<asynchronous suspension>
#2      Douyu.getRoomFullInfo (package:ice_live_viewer/utils/http/douyuparser.dart:124)
<asynchronous suspension>
#3      _FutureBuilderState._subscribe.<anonymous closure> (package:flutter/src/widgets/async.dart:628)
<asynchronous suspension>

[×] 我已经阅读了相关内容并且描述准确

**Comment by iiijam** [comment]
你好，斗鱼平台在轮播状态下是没有办法解析的 https://github.com/iiijam/ice_live_viewer#%E9%83%A8%E5%88%86%E9%93%BE%E6%8E%A5%E6%97%A0%E6%B3%95%E6%92%AD%E6%94%BE

**Comment by PieJEed** [comment]
（不懂就问）大佬，轮播状态是指当前直播间在轮播还是指主播开启了轮播模式。因为下午我提issue时例子直播间是直播的

**Comment by iiijam** [comment]
具体机制是斗鱼后端判定的，现在使用的这个接口没法获取
