### ISSUE TITLE
[Enhancement] Migrate to package:media_kit

### ISSUE THREAD

**Issue by alexmercerind** [iiijam/ice_live_viewer#26]
Hi @iiijam,

You should use [package:media_kit](https://github.com/alexmercerind/media_kit) for video playback in your application.
It has far-bar better performance & stability as compared to any other video/audio package. It also offers support for all platforms.

![](https://user-images.githubusercontent.com/28951144/233479464-97bed4ed-2619-4509-a747-a9462bc07128.png)

It is recommended replacement for package:dart_vlc.

These performance improvements were not feasible with VLC core. The size of package is also lesser.

**Comment by Xmarmalade** [comment]
Hello, thank you for the reminder. This project was written when I was just learning Flutter, which made the entire project very messy. I plan to completely rewrite this project.
