### ISSUE TITLE
[bug]斗鱼有个直播看不了，无法播放

### ISSUE THREAD

**Issue by Pulut** [iiijam/ice_live_viewer#3]
https://www.douyu.com/694630
这个地址，加进去之后，点击就没反应了，不会弹出选择清晰度的窗口
用了vlc那个临时解决方案，直接程序就打不开了

**Comment by iiijam** [comment]
这个是个轮播，现在用的这个接口没法获取（另外的pc接口需要运行JavaScript）`{'error': 742017, 'msg': '后端服务异常', 'data': ''}`，后续会增加可自行部署的api
