### ISSUE TITLE
[bug]虎牙的直播间没办法添加

### ISSUE THREAD

**Issue by Apple1314** [iiijam/ice_live_viewer#5]
没办法添加虎牙的直播间，会出现下面的错误

![This is an image](https://imgse.com/i/vhA9OA)

**Comment by Apple1314** [comment]
https://imgse.com/i/vhA9OA

**Comment by iiijam** [comment]
应该是没初始化，你可以先在右侧菜单打开设置把虎牙和哔哩哔哩的设置点一下，预计下个版本修复

**Comment by Apple1314** [comment]
谢谢 ，可以了，感谢大佬，期待大佬的安卓版

**Comment by iiijam** [comment]
fixed https://github.com/iiijam/ice_live_viewer/commit/c106754acd90ba7405b3722ff739eae75fcfc2c7
