### ISSUE TITLE
[request]关于虎牙一起看和直播显示问题

### ISSUE THREAD

**Issue by Apple1314** [iiijam/ice_live_viewer#6]
一起看看不了，不知道大佬能不能修复。

主要是没有直播显示的问题，关注的有点多，没办法直接看到是否直播，需要一个一个点才行

**Comment by iiijam** [comment]
请提供一些一起看的例子，我会尽力尝试
另外，主播没有开播，前面是有一个`disconnected`的，不过这个提示确实不是很好，后续会优化

**Comment by Apple1314** [comment]
> 请提供一些一起看的例子，我会尝试另外一些 ，主播没有开播，是有一个`disconnected`这个的，不过提示确实不是很好，会改善

比如这个一起看：https://www.huya.com/11342412，添加完之后播放总是播放一秒的时间就暂停了，点击继续播放也没办法观看，大佬你可以看一下这个视频：https://streamja.com/Av9O9。我试了几个直播间都是不可以的，应该是一起看的都不行。

好的，谢谢大佬，毕竟有个清晰的主播是否直播会更方便的观看

**Comment by Apple1314** [comment]
> 请提供一些一起看的例子，我会尽力尝试 另外，主播没有开播，前面是有一个`disconnected`的，不过这个提示确实不是很好，后续会优化

视频在线链接：https://streamja.com/Av9O9

**Comment by iiijam** [comment]
经过检查，这个不能看的原因是虎牙的服务器403，没法控制
