### ISSUE TITLE
安卓0.3.5版本选择“深色”模式，重启app后会自动回归为“明亮”模式[bug]

### ISSUE THREAD

**Issue by Httperrors** [iiijam/ice_live_viewer#8]
**描述错误**
“深色”模式不会被保存

**重现**
重现该行为的步骤。
1. 转到 '设置'
2. 点击 '主题'
3. 向下滚动到 '深色'，重启app后
4. 主题回滚到‘浅色’模式

**预期的行为**
使“深色”模式可以被保存

**屏幕截图**
无

**设备信息（请填写以下信息）：**
- 操作系统： 安卓
- 版本： 12

**额外的背景**
在手机与平板上均出现此现象。

[X] 我已经阅读了相关内容并且描述准确

**Comment by iiijam** [comment]
已在 cedd5d6418620fcb8dbaa041b81cee7aba4cecf5 提交,会随下个版本发布而修复
