### ISSUE TITLE
[bug]为什么错误无法观看

### ISSUE THREAD

**Issue by Apple1314** [iiijam/ice_live_viewer#9]
像斗鱼的一起看，总是会时不时的出现这种错误问题，有时错误有时没问题
[图片1](https://s4.aconvert.com/convert/p3r68-cdx67/a28dl-8sx9q.svg)
[图片2](https://s4.aconvert.com/convert/p3r68-cdx67/amag3-ivz84.svg)
[图片3](https://s4.aconvert.com/convert/p3r68-cdx67/a7kn5-8x4qw.svg)

**Comment by iiijam** [comment]
程序不对所有直播间提供可用性保证：[参见readme](https://github.com/iiijam/ice_live_viewer#%E9%83%A8%E5%88%86%E9%93%BE%E6%8E%A5%E6%97%A0%E6%B3%95%E6%92%AD%E6%94%BE)
另外，一个错误报告最好能提供比较详细的信息
